# Generated by Django 4.2 on 2023-05-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
        ("tags", "0001_initial"),
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("name",),
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                help_text="Выберите ингредиент рецепта",
                on_delete=django.db.models.deletion.CASCADE,
                to="ingredients.ingredient",
                verbose_name="Ингредиент рецепта",
            ),
        ),
        migrations.AlterField(
            model_name="tagrecipe",
            name="tag",
            field=models.ForeignKey(
                help_text="Выберите из списка тег",
                on_delete=django.db.models.deletion.CASCADE,
                to="tags.tag",
                verbose_name="Тег",
            ),
        ),
    ]
